name = "worker1.reacher.dev"

[rabbitmq]
url = "amqp://guest:guest@localhost:5672"
# Queue name to consume messages from.
# 
# Queues names are in the format "check.<verif_method>.<provider>", where:
# - <verif_method> is the verification method to use. It can be "Smtp",
# "Headless", or "Api". Note that not all verification methods are
# available for all providers. For example, currently the Headless method
# is not available for Gmail. However, the Smtp method is available for
# all providers. The "*" wildcard can be used to match any verification
# method.
# - <provider> is the email provider to verify. It can be "gmail", "yahoo",
# "hotmail", or "*". The "*" provider is a wildcard that matches any
# provider.
# 
# The queue name MUST be one of the following:
# - "check.*.gmail": subcribe exclusively to Gmail emails.
# - "check.*.yahoo": subcribe exclusively to Yahoo emails, both Headless and SMTP.
# - "check.Smtp.yahoo": subcribe exclusively to Yahoo emails where the verification method is explicity set to SMTP.
# - "check.Headless.yahoo": subcribe exclusively to Yahoo emails where the verification method is unset, or set to Headless (default method).
# - "check.*.hotmail.*": subcribe exclusively to Hotmail emails, both B2B and B2C, both Headless and SMTP.
# - "check.*.hotmail.b2b": subcribe exclusively to B2B Hotmail emails, both Headless and SMTP.
# - "check.*.hotmail.b2c": subcribe exclusively to B2C Hotmail email (@outlook, @live, @hotmail), both Headless and SMTP.
# - "check.Smtp.hotmail.b2c": subcribe exclusively to B2C Hotmail email (@outlook, @live, @hotmail) whose verification method is explicity set to SMTP.
# - "check.Headless.hotmail.b2c": subcribe exclusively to B2C Hotmail email (@outlook, @live, @hotmail) whose verification method is unset, or set to Headless (default method).
# 	- "check.Smtp.#": subcribe any to email whose default verification method is SMTP.
# - "check.Headless.#": subcribe any to email whose default verification method is Headless.
# - "check.#": subcribe any to email.
queue = "check.#"
concurrency = 20

# Throttle the maximum number of requests per second, per minute, per hour, an
# per day for this worker.
# All fields are optional, comment them out to disable the limit.
[throttle]
# max_requests_per_second = 20
max_requests_per_minute = 100
# max_requests_per_hour = 1000
max_requests_per_day = 20000

[db]
url = "postgresql://localhost/reacher_worker_db"
